[database]
host = 127.0.0.1
port = 5432
database = taskdb
user = tamim
password = {{ env "DB_PASSWORD" }}
sslmode = disable

[data]
# Any fields in the data section are available in migration templates
# prefix = foo
